name: Deploy PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: analisi1.tex
      - name: Copy
        run: |
          mkdir out
          cp ./analisi1.pdf ./out/analisi1.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: analisi1
          path: out/analisi1.pdf
      - name: Deploy
        uses: Sardiniangale/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: out
      
